### ISSUE TITLE
ChoiseParser in docs

### ISSUE THREAD

**Issue by KuzyaGlebkin** [copper-leaf/kudzu#10]
[It says here](https://github.com/copper-leaf/kudzu/blob/86a8d251f2b93a51becf823d27ce5655e3307eab/docs/src/orchid/resources/homepage.md?plain=1#L163) about the `ChoiceParser`, but I didn't find it in the package.
Was one of [these parsers](https://github.com/copper-leaf/kudzu/tree/86a8d251f2b93a51becf823d27ce5655e3307eab/kudzu-core/src/commonMain/kotlin/com/copperleaf/kudzu/parser/choice) meant?

**Comment by cjbrooks12** [comment]
Good catch, yes, it seems I never updated the docs with this change. You'll want to use `ExactChoiceParser()` or `PredictiveChoiceParser()` instead of `ChoiceParser()`.

I'm preparing to update this library to 1.9.21, so I'll get the docs updated with that release.

**Comment by cjbrooks12** [comment]
Fixed in bfc9143f5084e5de46e3633624a83976e544edaa
