### ISSUE TITLE
Error in docs. Chapter Building Parsers

### ISSUE THREAD

**Issue by KuzyaGlebkin** [copper-leaf/kudzu#11]
[This code](https://github.com/copper-leaf/kudzu/blob/86a8d251f2b93a51becf823d27ce5655e3307eab/docs/src/orchid/resources/homepage.md?plain=1#L174) generates an error. Perhaps `val output = statement.parse(ParserContext.fromString("one two 1234 asdf 56 qwerty 7890"))` was meant?

**Comment by cjbrooks12** [comment]
Fixed in bfc9143f5084e5de46e3633624a83976e544edaa
