### ISSUE TITLE
How to combine MappedParser with Choises?

### ISSUE THREAD

**Issue by tcoopman** [copper-leaf/kudzu#3]
Let's say I have 2 `MappedParser`s that either parse to `A` or `B`. 
I want to try to parse `A` but that can fail and when it fails I want to return `B`

How can I have a `ChoiceParser` return `A` and `B`?

```kotlin

val parser = MappedParser(
  ExactChoiceParser(aParser, bParser)
) {
// how do I get the value of either the aParser or the bParser here?
}
```

**Comment by tcoopman** [comment]
couldn't a choice node have `left` or `right` that can be null? Like the maybeNode has an optional?

**Comment by cjbrooks12** [comment]
I've had in mind to make it a bit more type-safe with a `left/right`-type monad node, but just haven't gotten around to it yet. I've recently done that with the `SequenceNode`, but a safer `ChoiceNode` is going to be a bit more verbose. I would happily accept a PR to add this, though.

For now, you'll ultimately have to cast the node to the appropriate type. It doesn't really give enough information to determine which specific parser was chosen, unless you manually wrap each choice with a `NamedParser`.

**Without wrapping (checking node types directly)**
```kotlin
val aParser = AnyCharParser()
val bParser = AnyTokenParser()

val parser: Parser<ValueNode<Any>> = MappedParser(
    ExactChoiceParser(aParser, bParser)
) { choiceNode: ChoiceNode ->
    when(val node = choiceNode.node) {
        is CharNode -> {
            // from aParser
            node.char
        }
        is TextNode -> {
            // from bParser
            node.text
        }
        else -> { error("should never get here") }
    }
}
```

**With wrapping**
```kotlin
val aParser = NamedParser(AnyCharParser(), "a")
val bParser = NamedParser(AnyTokenParser(), "b")

val parser: Parser<ValueNode<Any>> = MappedParser(
    ExactChoiceParser(aParser, bParser)
) { choiceNode: ChoiceNode ->
    val wrapped = choiceNode.node as NamedNode<*>
    
    when(wrapped.name) {
        "a" -> {
            // from aParser
            val wrappedNode = wrapped.node as CharNode
            wrappedNode.char
        }
        "b" -> {
            // from bParser
            val wrappedNode = wrapped.node as TextNode
            wrappedNode.text
        }
        else -> { error("should never get here") }
    }
}
```

**Comment by tcoopman** [comment]
Thanks, I can work around with that. I do have an other question, but I'll open an other issue for it
