### ISSUE TITLE
How to let a `ExactChoiceParser` backtrack completely for the failed first parser.

### ISSUE THREAD

**Issue by tcoopman** [copper-leaf/kudzu#4]
I have some code like this

```kotlin
ExactChoiceParser(
  SequenceParser(
    okParser,
    problemParser,
  ),
  TimesParser(AnyCharParser(), 100)
)
```

The problem is that I have some text to parse, but most of it is based on position. So I'm using `TimesParser` a lot. Now, when the `SequenceParser` fails because of the `problemParser`, I get to the `TimesParser` but now my parsing position isn't where I would want it.

I'd like to continue parsing as if the `okParser` did not happen.

**Comment by cjbrooks12** [comment]
Kudzu was intentionally designed to not have or need explicit backtracking. Instead, it passes around an immutable `ParserContext` which maintains the source position, and the internal position isn't modified and backtracked in a conventional manner. It shouldn't be able to be modified by a failed parser to fall out of sync, so I'm a bit confused as to how this is happening. 

Could you create a repo with a minimal test case so I can take a closer look?

**Comment by tcoopman** [comment]
You're right, it was a mistake on my part. Was a bit hard to debug, but had an incorrect count.

Thanks!
